language: python
python:
  - "2.7"
  - "3.5"
before_script:
  - pip install -U -r test_requirements.txt
script:
  - py.test --doctest-modules --pep8 --cov --cov-report term-missing --hypothesis-profile ci --ignore virtualenv
after_success:
  - coveralls